db:
 image: kalemo/couchdb:2.0.0
 ports:
  - "5984:5984"
 environment:
  - COUCHDB_USER=summer
  - COUCHDB_PASSWORD=123456

app:
 image: ibmcom/swift-ubuntu
 ports:
  - "8080:8080"
 volumes:
  - .:/Users/summerbarclay/galvanize/unit-3/swift/FoodTruck/FoodTruckAPI
 command: bash -c "cd /Users/summerbarclay/galvanize/unit-3/swift/FoodTruck/FoodTruckAPI && swift package clean && swift build --configuration release && ./.build/debug/FoodTruckServer"
 links:
  - db:localhost
